### ISSUE TITLE
Gauging Interest

### ISSUE THREAD

**Issue by ecwyne** [nodeschool/san-luis-obispo#1]
Are you in SLO and interested in learning Javascript/Node.js/io.js? Leave a comment here and let us know and we can set up a time to meet up and teach you! If you already know javascript that's no issue, let us know if you're interested in teaching/mentoring [here](https://github.com/nodeschool/san-luis-obispo/issues/2)!

**Comment by noahdietz** [comment]
Hey there! I'm a third year CSC major at Poly, and I need to learn Node for my internship this summer. I'm already familiar with Javascript. If y'all are available to help me out, I'd really appreciate it!

**Comment by ecwyne** [comment]
Awesome @noahdietz ! Just sent you an email with additional details!
