### ISSUE TITLE
Asynchronous HTTP Requests

### ISSUE THREAD

**Issue by noahdietz** [nodeschool/san-luis-obispo#3]
Hello!

I was working through the learnyounode tutorials and I just finished the Asynchronous HTTP Requests lesson. I got a working solution but wondered about best practices.

I solved the issue by nesting my http.get requests in the callbacks of the others, as so
![screen shot 2015-06-05 at 8 40 03 am](https://cloud.githubusercontent.com/assets/6644735/8009557/86813ed2-0b5e-11e5-9d81-2f4e8e790983.png)

However, the official solution just placed the request into a function and passed it the index in a loop to get the URLS from argv, as so

``` javascript
var http = require('http')
var bl = require('bl')
var results = []
var count = 0

function printResults () {
  for (var i = 0; i < 3; i++)
    console.log(results[i])
}

function httpGet (index) {
  http.get(process.argv[2 + index], function (response) {
    response.pipe(bl(function (err, data) {
      if (err)
        return console.error(err)

      results[index] = data.toString()
      count++

      if (count == 3)
        printResults()
    }))
  })
}

for (var i = 0; i < 3; i++)
  httpGet(i)
```

Which would be the better implementation? It asked not to use the async module, so I'm guessing that using the async module would be the best way to do this in general.

Also, is posting questions on here OK? Are the pictures fine or should I share code differently? 

Thanks!

**Comment by ecwyne** [comment]
I can totally take a look at this later today. If you post it here, only people looking at San Luis Obispo will see it. You can also post questions at https://github.com/nodeschool/discussions and the entire nodeschool community discusses questions there!

**Comment by ecwyne** [comment]
You can take a look at other `learnyounode` issues here: https://github.com/nodeschool/discussions/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Alearnyounode+

The pictures are useful for seeing the code but I'd probably use [markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) to copy and paste it in so that others can copy and paste the text directly.

**Comment by ecwyne** [comment]
To answer your original question, your solution will take about ~3x as long as the official solution, depending on network latency. To demonstrate this point, imagine that each http request takes 5 seconds to load. Your solution would send the first request, wait 5 seconds, THEN send the second request, wait 5 seconds, THEN send the third request. The official solution sends all three requests at once and then waits until ALL of the requests return (`if (count == 3)`) and prints out the results in the order they were SENT, NOT the order they were RECEIVED.

**Comment by ecwyne** [comment]
Also, I updated your original comment so that the official solution is shown using markdown. If you click on the pencil icon on the top right you can see how to correctly highlight javascript syntax using markdown.

Let me know if you have any other questions! Looks like you're doing well!

**Comment by noahdietz** [comment]
Ahhh I see. Essentially, my solution wasn't asynchronous at all! haha That makes sense, thank you for the clarification!

I appreciate the editing example, I'll use markdown from now on!

**Comment by ecwyne** [comment]
Technically speaking, your solution was asynchronous, meaning that your application could work on other things while it waited for each http request to return, but it was making those requests serially (one after another) as opposed to in parallel (simultaneously)
